-- Understanding the data
SELECT *
FROM tickets
LIMIT 100;


-- Question 1: What is the total income generated by the business?
SELECT SUM(precio_total) AS ingreso_total
FROM tickets;



-- Question 2: What has been the trend in monthly income?
SELECT strftime('%Y-%m', fecha) AS mes, SUM(precio_total) AS ingreso_mensual
FROM tickets
GROUP BY mes
ORDER BY mes;
